# Generated by Django 3.0.5 on 2020-05-20 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
    ]
