# Generated by Django 3.0.5 on 2020-05-21 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0029_order_ref_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='received',
            new_name='recieved',
        ),
    ]
