# Generated by Django 3.0.5 on 2020-05-21 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0030_auto_20200521_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='recieved',
            new_name='received',
        ),
    ]
